### PR TITLE
Update docs for custom bouncer

### PR DESCRIPTION
**Pull request by sbs2001**
Documents https://github.com/crowdsecurity/cs-custom-bouncer/pull/36

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Updated docs to reflect the update + pre release out.

**Comment by rr404** [comment]
Where are we on that doc? is it ready for a merge? or does it need further updates ?

**Comment by LaurenceJJones** [comment]
Waiting for the bouncer to be released, as it hasnt done an update in a while

**Comment by LaurenceJJones** [comment]
Please merge main as docusarus v3 has been integrated

**Pull request closed without merging**
