### PR TITLE
Update contribution docs to provide local development setup

### PR DESCRIPTION
**Pull request by nanikjava**
Tested our `crowdsec` locally by checking out the `master` branch but found out the steps to set it locally using local IDE is not straightfoward. Thought of creating a PR with the steps to helped other developers who are interested to contribute code.

### CODE REVIEW

**Comment by buixor** [comment]
Hello @nanikjava !

Thanks for the merge request !
Did you look at the `./test.sh` from within the release directory to setup a test environment ? this is what we are using often when developing :+1: 

Please let me know if you feel this does the job :)

**Comment by nanikjava** [comment]
@buixor checked both on `crowdsec` and `crowdsec-docs` repo there is no `test.sh` file ? which repo does this file exist ?

**Comment by buixor** [comment]
ah sorry, it's not documented : when you do "make release", inside the release directory you will find a `test.sh` script that if called is going to do a local/minimal setup in the "tests" directory

**Comment by nanikjava** [comment]
@buixor Looks like it's working, will repeat the process and make sure it all works fine. Will update the document to use this step. Thanks

**Comment by buixor** [comment]
thank you very much for your help

**Comment by AlteredCoder** [comment]
Hello @nanikjava, the script is named `test_env.sh` and is embed in the [`tar.gz` release](https://github.com/crowdsecurity/crowdsec/releases/download/v1.1.1/crowdsec-release.tgz)

**Comment by nanikjava** [comment]
@AlteredCoder Thanks. I've done the steps and looks like there are still few more steps that are required to make the local development machine fully function.

@buixor Will update this https://docs.crowdsec.net/Crowdsec/v1/write_configurations/requirements/ page to add more information.

**Comment by nanikjava** [comment]
@buixor PR updated with the latest changes for the doc.

**Comment by buixor** [comment]
Thanks again for the contribution.

However, the `test_env.sh` script already takes care of registering the machine, so you don't have to :+1:

**Review by buixor — APPROVED** [review]

**Comment by buixor** [comment]
awesome, thanks !

**Pull request merged**
