### PR TITLE
A more advanced telegram example

### PR DESCRIPTION
**Pull request by jebabin**
This example put the shodan as inline_keyboard and add a link to crowdsec cti as well

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
There may be multiple decisions so it may break links you could do
```
          [
{{range . -}}
{{range .Decisions -}}
              {
                  "text": "See {{.Value}} on shodan.io",
                  "url": "https://www.shodan.io/host/{{.Value}}"
              },
              {
                  "text": "See {{.Value}} on crowdsec.net",
                  "url": "https://app.crowdsec.net/cti/{{.Value}}"
              },
{{end -}}
{{end -}}
          ]
```

**Comment by jebabin** [comment]
Thanks @LaurenceJJones, I slightly changed it to add one row of inline_keyboard per decision.
It's still not perfect as it will not work with ranges (the original version is not better on this).
I'm wondering if I should change crowdsec-docs/crowdsec-docs/docs/notification_plugins/telegram.md instead of crowdsec-docs/versioned_docs/version-v1.4.0/notification_plugins/telegram.md ?

**Comment by LaurenceJJones** [comment]
Just checking inline_keyboard can be array of arrays?

**Comment by jebabin** [comment]
Yes inline_keyboard can be array of array: https://core.telegram.org/bots/api#inlinekeyboardmarkup
First level define "lines" and second level "columns"

**Pull request merged**
