### PR TITLE
📝 Console Security Engines

### PR DESCRIPTION
**Pull request by ziracmo**
# 📝  Console Security Engines documentation

> **Waiting for the Introduction PR (branch: [introduce-console-documentation](https://github.com/crowdsecurity/crowdsec-docs/tree/introduce-console-documentation)) from @TheCrowdsecMatt to be deployed to set this PR as Ready.**

New documentation page concerning the CrowdSec Console. Here are the latest pages concerning the Security Engines page. 

image

- The following pages are still unversioned and are waiting for a review.
- Every image concerning this documentation is in dark mode 🌔 

## How to test it?

- Go on the documentation et use this path (/u/console/security_engines/dashboard) to begin review.

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
setting to ready to review for github actions

**Comment by ziracmo** [comment]
> setting to ready to review for github actions

@LaurenceJJones. If the PR is in draft, it's for good reasons, as I'm not done yet.

**Comment by LaurenceJJones** [comment]
> > setting to ready to review for github actions
> 
> @LaurenceJJones. If the PR is in draft, it's for good reasons, as I'm not done yet.

sorry you did request a review and to make it easier we have a aws action but i can bring down changes locally for now

**Comment by ziracmo** [comment]
> > > setting to ready to review for github actions
> > 
> > 
> > @LaurenceJJones. If the PR is in draft, it's for good reasons, as I'm not done yet.
> 
> sorry you did request a review and to make it easier we have a aws action but i can bring down changes locally for now

Sorry, I will remove you from the reviewers until it's ready. As the PR is not the target `main`, it won't trigger the action.

**Review by LaurenceJJones — APPROVED** [review]

**Pull request merged**
