### PR TITLE
feat(cti): :memo: CTI doc - Introduction

### PR DESCRIPTION
**Pull request by ziracmo**
The first page of the CTI documentation. This page will inform the user about the CTI, what it is, and its benefits.

image
image
Capture d’écran 2024-11-18 à 15 04 09

The pages are coming in following PRs:
- Advanced filtering with facet
- IP Details page

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
any reason why this wouldnt live or be incorporated into the https://docs.crowdsec.net/u/cti_api/getting_started and https://docs.crowdsec.net/u/cti_api/intro pages?

**Review by rr404 — APPROVED** [review]
lgtm - retours pris en compte dans dernière PR

**Comment by ziracmo** [comment]
* **#676** <a href="https://app.graphite.dev/github/pr/crowdsecurity/crowdsec-docs/676?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#675** <a href="https://app.graphite.dev/github/pr/crowdsecurity/crowdsec-docs/675?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#674** <a href="https://app.graphite.dev/github/pr/crowdsecurity/crowdsec-docs/674?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/crowdsecurity/crowdsec-docs/674?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by ziracmo** [comment]
### Merge activity

* **Nov 25, 3:23 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/crowdsecurity/crowdsec-docs/674).

**Pull request merged**
